name: .NET Core

on:
  push:
    branches: [ master, dev, Herblore ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/web/Web.csproj
    - name: Use Node.js
      uses: actions/setup-node@v2.3.0
      with:
        node-version: '12.x'
    - name: Compile React
      run: |
        cd src/web/WebApp
        npm install
    - name: Build
      run: dotnet build --configuration Release --no-restore src/web/Web.csproj
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
